### ISSUE TITLE
image_to_osd: tesseract is not installed or it's not in your path

### ISSUE THREAD

**Issue by rola93** [madmaze/pytesseract#134]
Hello

I'm running pytesseract on Ubuntu 16.04 and pytesseract==0.1.7, over python 3.6.4. `tesseract --version `shows:
```
tesseract 3.04.01
 leptonica-1.73
  libgif 5.1.2 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.4 : libopenjp2 2.1.0

```

When I run image_to_string (`print(image_to_string(img, lang='spa'))`) everything goes right. However, when I run image_to_osd (`print(image_to_osd(img, lang='spa'))`) I get 'TesseractNotFoundError: tesseract is not installed or it's not in your path'.

The error occurs on `pytesseract.py`, near line 204:

```
        try:
            run_tesseract(**kwargs)
            filename = kwargs['output_filename_base'] + os.extsep + extension
            with open(filename, 'rb') as output_file:
                if return_bytes:
                    return output_file.read()
                return output_file.read().decode('utf-8').strip()
        except OSError as e:
            print("------------") # I added this
            print(e) # I added this
            print("------------") # I added this
            raise TesseractNotFoundError()

```
Then, before it breaks, it prints:

```
------------
[Errno 2] No such file or directory: '/tmp/tess_uadx0m7o_out.osd'
------------
```

What is happening here?

Thanks

**Comment by int3l** [comment]
Hi @rola93  and thanks for reporting the issue.
Apparently there is a problem with the file name format for the osd version.
Do you use any specific options or custom config other then the lang argument?

**Comment by rola93** [comment]
Nope. I used just those lines

Thanks for your reply!

El 29 jun. 2018 6:20 PM, int3l <notifications@github.com> escribió:

Hi @rola93<https://github.com/rola93> and thanks for reporting the issue.
Apparently there is a problem with the file name format for the osd version.
Do you use any specific options or custom config other then the lang argument?

**Comment by int3l** [comment]
I can't help if there is no sample image that causes the issue.
Also please try newer version of tesseract 3.05+ or 4.0+

**Comment by rola93** [comment]
Thanks for your reply!
I didn't try your update yet, and I didn't update tesseract, so now I have a minimal working example showing the bug, here it goes:

```
from scipy.misc.pilutil import imread
from pytesseract import image_to_osd, image_to_string
img = imread('./example/example.png')
print("Getting string...\n")
print(image_to_string(img, lang='eng'))
print("Done!\ngetting OSD...\n")
print(image_to_osd(img, lang='eng'))
```




Its output is:

```
Getting string...

m mm "mm mm mmvs‘
om m Sr ‘50“ mm m M
A m um n .4, «. .r meu
mm ”mm \‘chsn: m .g 5m
Du “my! mmcnyn \le"
W m mm mm u mm m
Wm 5mm whdriwﬁ u my.

MW .\ mm mm mm
(mm man: a m: WWW

‘4
Done!
getting OSD...

------------
[Errno 2] No such file or directory: '/tmp/tess_sehpi3fm_out.osd'
------------
Traceback (most recent call last):
  File "/home/rola93/.pyenv/versions/project/lib/python3.6/site-packages/pytesseract/pytesseract.py", line 196, in run_and_get_output
    with open(filename, 'rb') as output_file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tess_sehpi3fm_out.osd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bug.py", line 7, in <module>
    print(image_to_osd(img, lang='eng'))
  File "/home/rola93/.pyenv/versions/project/lib/python3.6/site-packages/pytesseract/pytesseract.py", line 352, in image_to_osd
    return run_and_get_output(image, 'osd', lang, config, nice)
  File "/home/rola93/.pyenv/versions/project/lib/python3.6/site-packages/pytesseract/pytesseract.py", line 204, in run_and_get_output
    raise TesseractNotFoundError()
pytesseract.pytesseract.TesseractNotFoundError: tesseract is not installed or it's not in your path

```

The image I'm using is the following for this example is the following, nonetheless I'm getting this error with all the images I've tried. The example image is extracted from a quickly google search, I'm not expecting to have good results on it, just trying if it works.

![example](https://user-images.githubusercontent.com/25650996/42170542-3db0a9d6-7ded-11e8-8b2a-4b047c2aa5b1.png)

**Comment by int3l** [comment]
Ok, I tested the sample image. The updated version of pytesseract correctly raises TesseractError now :)
The specific pytesseract issue is fixed, but unfortunately there is a problem with the OSD recognition for this image.

Unfortunately I am not expert in Tesseract, so you should ask on stack overflow or in the Tesseract issue tracker about why tesseract itself throws and error with this type of images.

**Comment by int3l** [comment]
And actually, there are similar reports for those image already - look at tesseract-ocr/tesseract#1463, tesseract-ocr/tesseract#1701

**Comment by rola93** [comment]
Hello again

I installed the newer version from git as suggested (with `pip install git+https://github.com/madmaze/pytesseract.git` ) but the error is still the same.

In addition to it, I tried to upgrade to tesseract 3.05+. As far as I know, this must be installed from sources, since it's not available as a package. I spent a lot of hours with [this tutorial](https://medium.com/@lucas63/installing-tesseract-3-04-in-ubuntu-14-04-1dae8b748a32) [this other](https://lucacerone.net/2017/install-tesseract-3-0-5-in-ubuntu-16-04/) and [this documenation](https://github.com/tesseract-ocr/tesseract/wiki/Compiling) but it without success. So I went back to easy 3.04, easlly installable with sudo apt-get.

Then I realised that tesseract is not the problem itself (or at least it migth not be). The first image I tried (and reported here) failed because it is too small, it fails even from command line. However, with a larger simalar version (the image reported in [1463](https://github.com/tesseract-ocr/tesseract/issues/1463)) the bug is still there while the command line tool solves it propperly:

output for bug.py:

```
Getting string...

The (quick) [brown] {fox} jumps!
Over the $43,456.78 <lazy> #90 dog
& duck/goose, as 12.5% of E-mail
from aspammer@website.com is spam.
Der ,,schnelle” braune Fuchs springt
ﬁber den faulen Hund. Le renard brun
«rapide» saute par-dessus le chien
paresseux. La volpe marrone rapida
salta sopra i] cane pigro. El zorro
marrén répido salta sobre el perro
perezoso. A raposa marrom répida
salta sobre 0 C50 preguieoso.
Done!
getting OSD...

Traceback (most recent call last):
  File "bug.py", line 7, in <module>
    print(image_to_osd(img, lang='eng'))
  File "/home/rola93/.pyenv/versions/project/lib/python3.6/site-packages/pytesseract/pytesseract.py", line 353, in image_to_osd
    return run_and_get_output(*args)
  File "/home/rola93/.pyenv/versions/project/lib/python3.6/site-packages/pytesseract/pytesseract.py", line 201, in run_and_get_output
    with open(filename, 'rb') as output_file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tess_4v8tmuag_out.osd'

```

 while commandline solves it as follows:

 tesseract example/new_example.png stdout -l spa -psm 0
Page number: 0
Orientation in degrees: 0
Rotate: 0
Orientation confidence: 15.09
Script: Latin
Script confidence: 19.63

So if pytesseract is wrapper and tesseract is able to solve it, pytesseract should be able to do it too, shouldn't it?.

new_example.png is the following:

<img width="1116" alt="new_example" src="https://user-images.githubusercontent.com/25650996/42227022-e5dd6012-7eb6-11e8-821b-938b812c550f.png">

Sorry for my bad choice for first example, and thanks again.

**Comment by int3l** [comment]
Thanks for reporting this, I will check why the new image still produce error.

**Comment by int3l** [comment]
@rola93 hi, sorry for the delay.
Well, I just tested the latest version of pytesseract (again from github) and it works with the last (bigger) image.

I am using the github version of pytesseract and tesseract 4.0.0-beta.1.20180608 (latest available one).

I also tested with this command in terminal:
```bash
tesseract test.png out -l osd --psm 0
```
Both pytesseract and tesseract alone produce:
```
Page number: 0
Orientation in degrees: 0
Rotate: 0
Orientation confidence: 25.65
Script: Latin
Script confidence: 4.50
```

**Comment by rola93** [comment]
Thanks for your answer.

As I see it, tesseract it the only difference. However I think there is still an error: it works from command line but it doesn't from pytesseract. 

I'm a little bussy those days but I'll try upgrade to 3.05 at least (4.0 is in beta [according to this](https://github.com/tesseract-ocr/tesseract/releases)). I would also like you to at least try it on tesseract 3.04, just to understand what is happening.

Thank you in advance!

**Comment by int3l** [comment]
The problem is that tesseract 3.04 has different convention for the arguments (-psm vs --psm for 3.05+).
Also, when 3.04 fails to parse cli arguments, the process exit outs like a boss with status code 0 (a.k.a everything is good)...
